
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK1 = 4;
  public static final int MINUS = 7;
  public static final int QSTRING = 11;
  public static final int CM = 8;
  public static final int S = 2;
  public static final int EOF = 0;
  public static final int EURO = 9;
  public static final int SEP = 3;
  public static final int REAL = 13;
  public static final int PERC = 10;
  public static final int error = 1;
  public static final int UINT = 12;
  public static final int TK3 = 6;
  public static final int TK2 = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "S",
  "SEP",
  "TK1",
  "TK2",
  "TK3",
  "MINUS",
  "CM",
  "EURO",
  "PERC",
  "QSTRING",
  "UINT",
  "REAL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[4]=new String("TK1");
		TT[7]=new String("MINUS");
		TT[11]=new String("QSTRING");
		TT[8]=new String("CM");
		TT[2]=new String("S");
		TT[0]=new String("EOF");
		TT[9]=new String("EURO");
		TT[3]=new String("SEP");
		TT[13]=new String("REAL");
		TT[10]=new String("PERC");
		TT[1]=new String("error");
		TT[12]=new String("UINT");
		TT[6]=new String("TK3");
		TT[5]=new String("TK2");
	}
public String getTT(int i){return TT[i];}
}

