
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LITERS = 8;
  public static final int MOD = 16;
  public static final int PLUS = 9;
  public static final int CM = 15;
  public static final int STAR = 11;
  public static final int S = 5;
  public static final int RO = 13;
  public static final int UNITS = 21;
  public static final int FUEL = 23;
  public static final int DO = 18;
  public static final int RC = 14;
  public static final int BATTERY = 22;
  public static final int KWH = 7;
  public static final int EOF = 0;
  public static final int SEP = 2;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int USE = 17;
  public static final int START = 6;
  public static final int MAX = 12;
  public static final int REAL = 24;
  public static final int KM = 20;
  public static final int DONE = 19;
  public static final int TK2 = 4;
  public static final int TK1 = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TK1",
  "TK2",
  "S",
  "START",
  "KWH",
  "LITERS",
  "PLUS",
  "MINUS",
  "STAR",
  "MAX",
  "RO",
  "RC",
  "CM",
  "MOD",
  "USE",
  "DO",
  "DONE",
  "KM",
  "UNITS",
  "BATTERY",
  "FUEL",
  "REAL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[8]=new String("LITERS");
		TT[16]=new String("MOD");
		TT[9]=new String("PLUS");
		TT[15]=new String("CM");
		TT[11]=new String("STAR");
		TT[5]=new String("S");
		TT[13]=new String("RO");
		TT[21]=new String("UNITS");
		TT[23]=new String("FUEL");
		TT[18]=new String("DO");
		TT[14]=new String("RC");
		TT[22]=new String("BATTERY");
		TT[7]=new String("KWH");
		TT[0]=new String("EOF");
		TT[2]=new String("SEP");
		TT[10]=new String("MINUS");
		TT[1]=new String("error");
		TT[17]=new String("USE");
		TT[6]=new String("START");
		TT[12]=new String("MAX");
		TT[24]=new String("REAL");
		TT[20]=new String("KM");
		TT[19]=new String("DONE");
		TT[4]=new String("TK2");
		TT[3]=new String("TK1");
	}
public String getTT(int i){return TT[i];}
}

